config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :campaigns
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/campaign.rb
class Spree::Campaign < ActiveRecord::Base
  has_many :coupons
  belongs_to :promotion

  def coupon_codes
  end

  def has_coupon_code?(code)
    coupons.find { |c| c.code == code }.present?
  end

  def coupon_codes=(uploaded_coupons_file)
    return unless uploaded_coupons_file.present?
    File.open(uploaded_coupons_file.tempfile, "rb", encoding: 'ISO-8859-1') do |file|
      process_coupon_codes_file(file.readlines)
    end
  end

  private

  def process_coupon_codes_file(coupon_codes)
    return true unless coupon_codes.present?
    coupons << coupon_codes.map { |code| Spree::Coupon.create(code: code.strip) }
    update(coupons_processing: true)
    ProcessCoupons.perform_async(id, coupon_codes)
  end
end

app/models/spree/cart_handler_decorator.rb
Spree::PromotionHandler::Cart.class_eval do

  def activate
    promotions.each do |promotion|
      next if promotion.is_campaign
      if (line_item && promotion.eligible?(line_item)) || promotion.eligible?(order)
        promotion.activate(line_item: line_item, order: order)
      end
    end
  end

end

app/models/spree/coupon.rb
class Spree::Coupon < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :order
  has_one :promotion, through: :campaign

  validates :code, presence: true, uniqueness: true

  def used!
    update(used: true)
  end

  def self.by_code(code)
    where("lower(code) = ?", code.strip.downcase).first
  end

end

app/models/spree/coupon_handler_decorator.rb
Spree::PromotionHandler::Coupon.class_eval do
  attr_accessor :coupon

  def apply
   if order.coupon_code.present?
      @coupon = Spree::Coupon.by_code(order.coupon_code.strip.downcase)
      if campaign_coupon_used?
        set_error_code :coupon_code_already_used
      else
        assign_order_to_campaign_coupon

        if promotion.present? && promotion.actions.exists?
          handle_present_promotion(promotion)
        else
          if Spree::Promotion.with_coupon_code(order.coupon_code).try(:expired?)
            set_error_code :coupon_code_expired
          else
            set_error_code :coupon_code_not_found
          end
        end
      end
    end
    self
  end

  def determine_promotion_application_result
    # Check for a matching coupon code
    discount = order.all_adjustments.promotion.eligible.find { |promotion_action|
      promotion = promotion_action.source.promotion

      @coupon_code = order.coupon_code.downcase

      if promotion.is_campaign?
        promotion.campaigns.detect { |campaign| campaign.has_coupon_code?(@coupon_code) }
      elsif promotion.code
        promotion.code.downcase == @coupon_code
      end
    }
    if discount && discount.eligible
      @coupon.used! if @coupon

      order.update_totals
      order.persist_totals
      set_success_code :coupon_code_applied
    else
      # if the promotion exists on an order, but wasn't found above,
      # we've already selected a better promotion
      if order.promotions.with_coupon_code(order.coupon_code)
        set_error_code :coupon_code_better_exists
      else
        # if the promotion was created after the order
        set_error_code :coupon_code_not_found
      end
    end
  end

  private

  def campaign_coupon_used?
    @coupon && @coupon.used?
  end

  def assign_order_to_campaign_coupon
    @coupon.update(order: order) if @coupon
  end
end

app/models/spree/promotion_decorator.rb
Spree::Promotion.class_eval do
  has_many :campaigns

  def self.with_coupon_code(coupon_code)
    coupon = Spree::Coupon.by_code(coupon_code.strip.downcase)
    return coupon.promotion if coupon
    where("lower(#{self.table_name}.code) = ?", coupon_code.strip.downcase).first
  end

  def self.for_campaigns
    where(is_campaign: true)
  end
end

app/controllers/spree/admin/campaigns_controller.rb
module Spree
  module Admin
    class CampaignsController < ResourceController
    end
  end
end

app/views/spree/admin/campaigns/_coupons.html.erb
<tr id="<%= spree_dom_id(coupon) %>" data-hook="coupon_row" class="<%= cycle('odd', 'even')%>">
  <td class="align-left"><%= coupon.code %></td>
  <td class="align-left"><%= coupon.used %></td>
</tr>

app/views/spree/admin/campaigns/_form.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @campaign } %>

<div class='row'>
  <div class='alpha eight columns'>
    <%= f.field_container :title do %>
      <%= f.label :title %>
      <%= f.text_field :title, :class => 'fullwidth title' %>
    <% end %>

    <%= f.field_container :coupon_codes do %>
      <%= f.label :coupon_codes %>
      <%= f.file_field :coupon_codes %>
    <% end %>

    <%= f.field_container :promotions do %>
      <%= f.label :promotion_id, Spree.t(:promotion) %>
      <%= f.collection_select(:promotion_id, Spree::Promotion.for_campaigns, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2' }) %>
      <%= f.error_message_on :promotion %>
    <% end %>
  </div>
</div>

app/views/spree/admin/campaigns/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_campaign) %>
<% end %>

<%= render 'spree/admin/shared/promotion_sub_menu' %>

<%= form_for @campaign, :url => object_url, :method => :put do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/campaigns/index.html.erb
<% content_for :page_title do %>
  <%= Spree::Campaign.model_name.human(count: :many) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_campaign), spree.new_admin_campaign_path, :icon => 'plus' %>
  </li>
<% end %>

<%= render 'spree/admin/shared/promotion_sub_menu' %>

<table>
  <colgroup>
    <col style="width: 30%">
    <col style="width: 30%">
    <col style="width: 20%">
    <col style="width: 20%">
  </colgroup>
  <thead>
    <th><%= Spree::Campaign.human_attribute_name :title %></th>
    <th><%= Spree::Campaign.human_attribute_name :promotion %></th>
    <th><%= Spree::Campaign.human_attribute_name :coupons %></th>
    <th class='actions'></th>
  </thead>
  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to campaign.title, admin_campaign_path(campaign)  %></td>
        <td><%= campaign.promotion.try(:name) %></td>
        <td>
          <%= campaign.coupons.count %>
          <% if campaign.coupons_processing %>
          ( processing )
          <% end %>
        </td>
        <td class="actions">
          <%= link_to_edit campaign, :no_text => true %>
          <%= link_to_delete campaign, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/campaigns/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_campaign) %>
<% end %>

<%= render 'spree/admin/shared/promotion_sub_menu' %>

<%= form_for :campaign, :url => collection_url do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/campaigns/show.html.erb
<% content_for :page_title do %>
  <%= @campaign.title %>
<% end %>

<%= render 'spree/admin/shared/promotion_sub_menu' %>


<pre>
  TODO:
  Show stats, like number used, revenue, available coupons etc.
  Discuss the need for the list of coupons.
</pre>

<!-- <table class="index">
  <thead>
    <tr>
      <th class="align-left">Code</th>
      <th class="align-left">Used?</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "coupons", :collection => @campaign.coupons, :as => :coupon %>
  </tbody>
</table> -->